-- DDL: secuencias
CREATE SEQUENCE seq_nacionalidad START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_genero START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_apellido_orden START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_documento_identidad_tipo START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_contacto_medio START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_direccion_ubicacion_tipo START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_direccion_calle_tipo START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_direccion_ubicacion START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_direccion START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_persona START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_documento_identidad START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_personas_medios_contacto START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_persona_direcciones START WITH 1 INCREMENT BY 1;

